var composerList = [
    // this list should be a db table and grabbed on homepage load
    { id: 149, name: "John Adams", lat: 0, lng: 0 },
    { id: 130, name: "Thomas Adès", lat: 0, lng: 0 },
    { id: 216, name: "Isaac Albéniz", lat: 0, lng: 0 },
    { id: 27, name: "Tomaso Albinoni", lat: 0, lng: 0 },
    { id: 108, name: "George Antheil", lat: 0, lng: 0 },
    { id: 20, name: "Malcolm Arnold", lat: 0, lng: 0 },
    { id: 180, name: "Milton Babbitt", lat: 0, lng: 0 },
    { id: 87, name: "Johann Sebastian Bach", lat: 0, lng: 0 },
    { id: 192, name: "Carl Philipp Emanuel Bach", lat: 0, lng: 0 },
    { id: 109, name: "Johann Christian Bach", lat: 0, lng: 0 },
    { id: 21, name: "Mily Balakirev", lat: 0, lng: 0 },
    { id: 19, name: "Samuel Barber", lat: 0, lng: 0 },
    { id: 125, name: "Béla Bartók", lat: 0, lng: 0 },
    { id: 103, name: "Arnold Bax", lat: 0, lng: 0 },
    { id: 145, name: "Ludwig van Beethoven", lat: 50.7374, lng: 7.0982 },
    { id: 51, name: "Vincenzo Bellini", lat: 0, lng: 0 },
    { id: 210, name: "Alban Berg", lat: 0, lng: 0 },
    { id: 133, name: "Luciano Berio", lat: 0, lng: 0 },
    { id: 175, name: "Hector Berlioz", lat: 0, lng: 0 },
    { id: 135, name: "Leonard Bernstein", lat: 0, lng: 0 },
    { id: 195, name: "Franz Berwald", lat: 0, lng: 0 },
    { id: 47, name: "Heinrich Franz von Biber", lat: 0, lng: 0 },
    { id: 48, name: "Harrison Birtwistle", lat: 0, lng: 0 },
    { id: 68, name: "Georges Bizet", lat: 0, lng: 0 },
    { id: 106, name: "Ernest Bloch", lat: 0, lng: 0 },
    { id: 66, name: "Luigi Boccherini", lat: 0, lng: 0 },
    { id: 43, name: "Alexander Borodin", lat: 0, lng: 0 },
    { id: 132, name: "Pierre Boulez", lat: 0, lng: 0 },
    { id: 153, name: "Joly Braga Santos", lat: 0, lng: 0 },
    { id: 80, name: "Johannes Brahms", lat: 0, lng: 0 },
    { id: 169, name: "Benjamin Britten", lat: 0, lng: 0 },
    { id: 184, name: "Max Bruch", lat: 0, lng: 0 },
    { id: 2, name: "Anton Bruckner", lat: 0, lng: 0 },
    { id: 84, name: "Ferruccio Busoni", lat: 0, lng: 0 },
    { id: 73, name: "Dietrich Buxtehude", lat: 0, lng: 0 },
    { id: 86, name: "William Byrd", lat: 0, lng: 0 },
    { id: 56, name: "John Cage", lat: 0, lng: 0 },
    { id: 159, name: "Camargo Guarnieri", lat: 0, lng: 0 },
    { id: 163, name: "Elliott Carter", lat: 0, lng: 0 },
    { id: 123, name: "Emmanuel Chabrier", lat: 0, lng: 0 },
    { id: 9, name: "Marc-Antoine Charpentier", lat: 0, lng: 0 },
    { id: 61, name: "Ernest Chausson", lat: 0, lng: 0 },
    { id: 174, name: "Carlos Chávez", lat: 0, lng: 0 },
    { id: 120, name: "Luigi Cherubini", lat: 0, lng: 0 },
    { id: 152, name: "Frédéric Chopin", lat: 0, lng: 0 },
    { id: 170, name: "Aaron Copland", lat: 0, lng: 0 },
    { id: 139, name: "Arcangelo Corelli", lat: 0, lng: 0 },
    { id: 144, name: "John Corigliano", lat: 0, lng: 0 },
    { id: 128, name: "François Couperin", lat: 0, lng: 0 },
    { id: 31, name: "George Crumb", lat: 0, lng: 0 },
    { id: 71, name: "César Cui", lat: 0, lng: 0 },
    { id: 127, name: "Vincent d'Indy", lat: 0, lng: 0 },
    { id: 81, name: "Michael Daugherty", lat: 0, lng: 0 },
    { id: 105, name: "Claude Debussy", lat: 0, lng: 0 },
    { id: 193, name: "Léo Delibes", lat: 0, lng: 0 },
    { id: 8, name: "Frederick Delius", lat: 0, lng: 0 },
    { id: 50, name: "Josquin Des Prez", lat: 0, lng: 0 },
    { id: 206, name: "Karl Ditters von Dittersdorf", lat: 0, lng: 0 },
    { id: 112, name: "Ernst von Dohnányi", lat: 0, lng: 0 },
    { id: 89, name: "Gaetano Donizetti", lat: 0, lng: 0 },
    { id: 102, name: "John Dowland", lat: 0, lng: 0 },
    { id: 82, name: "Guillaume Dufay", lat: 0, lng: 0 },
    { id: 116, name: "Paul Dukas", lat: 0, lng: 0 },
    { id: 91, name: "Maurice Duruflé", lat: 0, lng: 0 },
    { id: 110, name: "Henri Dutilleux", lat: 0, lng: 0 },
    { id: 189, name: "Antonín Dvořák", lat: 0, lng: 0 },
    { id: 198, name: "Edward Elgar", lat: 0, lng: 0 },
    { id: 38, name: "George Enescu", lat: 0, lng: 0 },
    { id: 37, name: "Manuel de Falla", lat: 0, lng: 0 },
    { id: 53, name: "Gabriel Fauré", lat: 0, lng: 0 },
    { id: 74, name: "John Field", lat: 0, lng: 0 },
    { id: 12, name: "César Franck", lat: 0, lng: 0 },
    { id: 58, name: "Girolamo Frescobaldi", lat: 0, lng: 0 },
    { id: 136, name: "George Gershwin", lat: 0, lng: 0 },
    { id: 14, name: "Carlo Gesualdo", lat: 0, lng: 0 },
    { id: 151, name: "Orlando Gibbons", lat: 0, lng: 0 },
    { id: 32, name: "Alberto Ginastera", lat: 0, lng: 0 },
    { id: 95, name: "Philip Glass", lat: 0, lng: 0 },
    { id: 179, name: "Alexander Glazunov", lat: 0, lng: 0 },
    { id: 85, name: "Reinhold Glière", lat: 0, lng: 0 },
    { id: 156, name: "Mikhail Ivanovich Glinka", lat: 0, lng: 0 },
    { id: 92, name: "Christoph Willibald von Gluck", lat: 0, lng: 0 },
    { id: 1, name: "Karl Goldmark", lat: 0, lng: 0 },
    { id: 207, name: "Antonio Carlos Gomes", lat: 0, lng: 0 },
    { id: 16, name: "Henryk Górecki", lat: 0, lng: 0 },
    { id: 70, name: "Morton Gould", lat: 0, lng: 0 },
    { id: 29, name: "Charles Gounod", lat: 0, lng: 0 },
    { id: 99, name: "Percy Grainger", lat: 0, lng: 0 },
    { id: 76, name: "Enrique Granados", lat: 0, lng: 0 },
    { id: 162, name: "Edvard Grieg", lat: 0, lng: 0 },
    { id: 172, name: "Sofia Gubaidulina", lat: 0, lng: 0 },
    { id: 67, name: "George Frideric Handel", lat: 0, lng: 0 },
    { id: 42, name: "Howard Hanson", lat: 0, lng: 0 },
    { id: 201, name: "Roy Harris", lat: 0, lng: 0 },
    { id: 208, name: "Franz Joseph Haydn", lat: 0, lng: 0 },
    { id: 155, name: "Hans Werner Henze", lat: 0, lng: 0 },
    { id: 94, name: "Victor Herbert", lat: 0, lng: 0 },
    { id: 154, name: "Paul Hindemith", lat: 0, lng: 0 },
    { id: 158, name: "Vagn Holmboe", lat: 0, lng: 0 },
    { id: 75, name: "Gustav Holst", lat: 0, lng: 0 },
    { id: 200, name: "Arthur Honegger", lat: 0, lng: 0 },
    { id: 30, name: "Johann Nepomuk Hummel", lat: 0, lng: 0 },
    { id: 15, name: "Engelbert Humperdinck", lat: 0, lng: 0 },
    { id: 122, name: "Jacques Ibert", lat: 0, lng: 0 },
    { id: 217, name: "Charles Ives", lat: 0, lng: 0 },
    { id: 96, name: "Leoš Janáček", lat: 0, lng: 0 },
    { id: 23, name: "Clément Janequin", lat: 0, lng: 0 },
    { id: 148, name: "Scott Joplin", lat: 0, lng: 0 },
    { id: 63, name: "Dmitry Kabalevsky", lat: 0, lng: 0 },
    { id: 218, name: "Aram Khachaturian", lat: 0, lng: 0 },
    { id: 34, name: "Zoltán Kodály", lat: 0, lng: 0 },
    { id: 7, name: "Erich Wolfgang Korngold", lat: 0, lng: 0 },
    { id: 59, name: "Edouard Lalo", lat: 0, lng: 0 },
    { id: 88, name: "Orlande de Lassus", lat: 0, lng: 0 },
    { id: 194, name: "Ruggero Leoncavallo", lat: 0, lng: 0 },
    { id: 220, name: "Léonin", lat: 0, lng: 0 },
    { id: 26, name: "György Ligeti", lat: 0, lng: 0 },
    { id: 197, name: "Franz Liszt", lat: 0, lng: 0 },
    { id: 119, name: "Fernando Lopes-Graça", lat: 0, lng: 0 },
    { id: 10, name: "Jean-Baptiste Lully", lat: 0, lng: 0 },
    { id: 142, name: "Witold Lutoslawski", lat: 0, lng: 0 },
    { id: 114, name: "Edward MacDowell", lat: 0, lng: 0 },
    { id: 157, name: "Guillaume de Machaut", lat: 0, lng: 0 },
    { id: 77, name: "Gustav Mahler", lat: 0, lng: 0 },
    { id: 204, name: "Marin Marais", lat: 0, lng: 0 },
    { id: 177, name: "Benedetto Marcello", lat: 0, lng: 0 },
    { id: 187, name: "Alessandro Marcello", lat: 0, lng: 0 },
    { id: 11, name: "Bohuslav Martinů", lat: 0, lng: 0 },
    { id: 69, name: "Pietro Mascagni", lat: 0, lng: 0 },
    { id: 124, name: "Jules Massenet", lat: 0, lng: 0 },
    { id: 147, name: "Felix Mendelssohn", lat: 0, lng: 0 },
    { id: 150, name: "Olivier Messiaen", lat: 0, lng: 0 },
    { id: 64, name: "Francisco Mignone", lat: 0, lng: 0 },
    { id: 121, name: "Darius Milhaud", lat: 0, lng: 0 },
    { id: 164, name: "Ernest Moeran", lat: 0, lng: 0 },
    { id: 39, name: "Claudio Monteverdi", lat: 0, lng: 0 },
    { id: 196, name: "Wolfgang Amadeus Mozart", lat: 47.8014, lng: 13.0448 },
    { id: 181, name: "Modest Mussorgsky", lat: 0, lng: 0 },
    { id: 52, name: "Carl Nielsen", lat: 0, lng: 0 },
    { id: 111, name: "Luigi Nono", lat: 0, lng: 0 },
    { id: 28, name: "Jacob Obrecht", lat: 0, lng: 0 },
    { id: 117, name: "Johannes Ockeghem", lat: 0, lng: 0 },
    { id: 134, name: "Jacques Offenbach", lat: 0, lng: 0 },
    { id: 93, name: "Carl Orff", lat: 0, lng: 0 },
    { id: 115, name: "Johann Pachelbel", lat: 0, lng: 0 },
    { id: 3, name: "Niccolò Paganini", lat: 0, lng: 0 },
    { id: 214, name: "Giovanni Pierluigi da Palestrina", lat: 0, lng: 0 },
    { id: 5, name: "Arvo Pärt", lat: 0, lng: 0 },
    { id: 203, name: "Krzysztof Penderecki", lat: 0, lng: 0 },
    { id: 113, name: "Giovanni Battista Pergolesi", lat: 0, lng: 0 },
    { id: 219, name: "Pérotin", lat: 0, lng: 0 },
    { id: 40, name: "Astor Piazzolla", lat: 0, lng: 0 },
    { id: 202, name: "Francis Poulenc", lat: 0, lng: 0 },
    { id: 78, name: "Michael Praetorius", lat: 0, lng: 0 },
    { id: 185, name: "Sergei Prokofiev", lat: 0, lng: 0 },
    { id: 146, name: "Giacomo Puccini", lat: 0, lng: 0 },
    { id: 199, name: "Henry Purcell", lat: 0, lng: 0 },
    { id: 188, name: "Sergei Rachmaninoff", lat: 0, lng: 0 },
    { id: 178, name: "Jean-Philippe Rameau", lat: 0, lng: 0 },
    { id: 100, name: "Einojuhani Rautavaara", lat: 0, lng: 0 },
    { id: 57, name: "Maurice Ravel", lat: 0, lng: 0 },
    { id: 72, name: "Max Reger", lat: 0, lng: 0 },
    { id: 176, name: "Steve Reich", lat: 0, lng: 0 },
    { id: 173, name: "Ottorino Respighi", lat: 0, lng: 0 },
    { id: 90, name: "Wolfgang Rihm", lat: 0, lng: 0 },
    { id: 118, name: "Nikolai Rimsky-Korsakov", lat: 0, lng: 0 },
    { id: 215, name: "Joaquín Rodrigo", lat: 0, lng: 0 },
    { id: 107, name: "Ned Rorem", lat: 0, lng: 0 },
    { id: 60, name: "Gioachino Rossini", lat: 0, lng: 0 },
    { id: 140, name: "Albert Roussel", lat: 0, lng: 0 },
    { id: 45, name: "Camille Saint-Saëns", lat: 0, lng: 0 },
    { id: 143, name: "Antonio Salieri", lat: 0, lng: 0 },
    { id: 104, name: "Erik Satie", lat: 0, lng: 0 },
    { id: 97, name: "Domenico Scarlatti", lat: 0, lng: 0 },
    { id: 65, name: "Alessandro Scarlatti", lat: 0, lng: 0 },
    { id: 160, name: "Franz Schmidt", lat: 0, lng: 0 },
    { id: 137, name: "Alfred Schnittke", lat: 0, lng: 0 },
    { id: 62, name: "Arnold Schoenberg", lat: 0, lng: 0 },
    { id: 183, name: "Franz Schubert", lat: 0, lng: 0 },
    { id: 24, name: "William Schuman", lat: 0, lng: 0 },
    { id: 129, name: "Robert Schumann", lat: 0, lng: 0 },
    { id: 191, name: "Heinrich Schütz", lat: 0, lng: 0 },
    { id: 18, name: "Alexander Scriabin", lat: 0, lng: 0 },
    { id: 46, name: "Dmitri Shostakovich", lat: 0, lng: 0 },
    { id: 186, name: "Jean Sibelius", lat: 0, lng: 0 },
    { id: 211, name: "Bedrich Smetana", lat: 0, lng: 0 },
    { id: 212, name: "Fernando Sor", lat: 0, lng: 0 },
    { id: 166, name: "Louis Spohr", lat: 0, lng: 0 },
    { id: 209, name: "Carl Stamitz", lat: 0, lng: 0 },
    { id: 4, name: "Wilhelm Stenhammar", lat: 0, lng: 0 },
    { id: 101, name: "Karlheinz Stockhausen", lat: 0, lng: 0 },
    { id: 171, name: "Richard Strauss", lat: 0, lng: 0 },
    { id: 165, name: "Johann Strauss Jr", lat: 0, lng: 0 },
    { id: 190, name: "Igor Stravinsky", lat: 0, lng: 0 },
    { id: 33, name: "Josef Suk", lat: 0, lng: 0 },
    { id: 182, name: "Jan Pieterszoon Sweelinck", lat: 0, lng: 0 },
    { id: 49, name: "Karol Szymanowski", lat: 0, lng: 0 },
    { id: 213, name: "Toru Takemitsu", lat: 0, lng: 0 },
    { id: 126, name: "Thomas Tallis", lat: 0, lng: 0 },
    { id: 167, name: "Giuseppe Tartini", lat: 0, lng: 0 },
    { id: 54, name: "John Taverner", lat: 0, lng: 0 },
    { id: 79, name: "Pyotr Ilyich Tchaikovsky", lat: 0, lng: 0 },
    { id: 83, name: "Georg Philipp Telemann", lat: 0, lng: 0 },
    { id: 13, name: "Michael Tippett", lat: 0, lng: 0 },
    { id: 22, name: "Edgard Varèse", lat: 0, lng: 0 },
    { id: 36, name: "Ralph Vaughan Williams", lat: 0, lng: 0 },
    { id: 35, name: "Giuseppe Verdi", lat: 0, lng: 0 },
    { id: 205, name: "Tomás Luis de Victoria", lat: 0, lng: 0 },
    { id: 55, name: "Heitor Villa-Lobos", lat: 0, lng: 0 },
    { id: 98, name: "Antonio Vivaldi", lat: 0, lng: 0 },
    { id: 138, name: "Richard Wagner", lat: 0, lng: 0 },
    { id: 44, name: "William Walton", lat: 0, lng: 0 },
    { id: 168, name: "Carl Maria von Weber", lat: 0, lng: 0 },
    { id: 6, name: "Anton Webern", lat: 0, lng: 0 },
    { id: 131, name: "Kurt Weill", lat: 0, lng: 0 },
    { id: 41, name: "Charles-Marie Widor", lat: 0, lng: 0 },
    { id: 161, name: "Hugo Wolf", lat: 0, lng: 0 },
    { id: 17, name: "Iannis Xenakis", lat: 0, lng: 0 },
    { id: 141, name: "Eugene Ysaÿe", lat: 0, lng: 0 },
    { id: 25, name: "Alexander von Zemlinsky", lat: 0, lng: 0 },
];

export default composerList;