var composerList = [
    { id: 149, name: "John Adams" },
    { id: 130, name: "Thomas Adès" },
    { id: 216, name: "Isaac Albéniz" },
    { id: 27, name: "Tomaso Albinoni" },
    { id: 108, name: "George Antheil" },
    { id: 20, name: "Malcolm Arnold" },
    { id: 180, name: "Milton Babbitt" },
    { id: 87, name: "Johann Sebastian Bach" },
    { id: 192, name: "Carl Philipp Emanuel Bach" },
    { id: 109, name: "Johann Christian Bach" },
    { id: 21, name: "Mily Balakirev" },
    { id: 19, name: "Samuel Barber" },
    { id: 125, name: "Béla Bartók" },
    { id: 103, name: "Arnold Bax" },
    { id: 145, name: "Ludwig van Beethoven" },
    { id: 51, name: "Vincenzo Bellini" },
    { id: 210, name: "Alban Berg" },
    { id: 133, name: "Luciano Berio" },
    { id: 175, name: "Hector Berlioz" },
    { id: 135, name: "Leonard Bernstein" },
    { id: 195, name: "Franz Berwald" },
    { id: 47, name: "Heinrich Franz von Biber" },
    { id: 48, name: "Harrison Birtwistle" },
    { id: 68, name: "Georges Bizet" },
    { id: 106, name: "Ernest Bloch" },
    { id: 66, name: "Luigi Boccherini" },
    { id: 43, name: "Alexander Borodin" },
    { id: 132, name: "Pierre Boulez" },
    { id: 153, name: "Joly Braga Santos" },
    { id: 80, name: "Johannes Brahms" },
    { id: 169, name: "Benjamin Britten" },
    { id: 184, name: "Max Bruch" },
    { id: 2, name: "Anton Bruckner" },
    { id: 84, name: "Ferruccio Busoni" },
    { id: 73, name: "Dietrich Buxtehude" },
    { id: 86, name: "William Byrd" },
    { id: 56, name: "John Cage" },
    { id: 159, name: "Camargo Guarnieri" },
    { id: 163, name: "Elliott Carter" },
    { id: 123, name: "Emmanuel Chabrier" },
    { id: 9, name: "Marc-Antoine Charpentier" },
    { id: 61, name: "Ernest Chausson" },
    { id: 174, name: "Carlos Chávez" },
    { id: 120, name: "Luigi Cherubini" },
    { id: 152, name: "Frédéric Chopin" },
    { id: 170, name: "Aaron Copland" },
    { id: 139, name: "Arcangelo Corelli" },
    { id: 144, name: "John Corigliano" },
    { id: 128, name: "François Couperin" },
    { id: 31, name: "George Crumb" },
    { id: 71, name: "César Cui" },
    { id: 127, name: "Vincent d'Indy" },
    { id: 81, name: "Michael Daugherty" },
    { id: 105, name: "Claude Debussy" },
    { id: 193, name: "Léo Delibes" },
    { id: 8, name: "Frederick Delius" },
    { id: 50, name: "Josquin Des Prez" },
    { id: 206, name: "Karl Ditters von Dittersdorf" },
    { id: 112, name: "Ernst von Dohnányi" },
    { id: 89, name: "Gaetano Donizetti" },
    { id: 102, name: "John Dowland" },
    { id: 82, name: "Guillaume Dufay" },
    { id: 116, name: "Paul Dukas" },
    { id: 91, name: "Maurice Duruflé" },
    { id: 110, name: "Henri Dutilleux" },
    { id: 189, name: "Antonín Dvořák" },
    { id: 198, name: "Edward Elgar" },
    { id: 38, name: "George Enescu" },
    { id: 37, name: "Manuel de Falla" },
    { id: 53, name: "Gabriel Fauré" },
    { id: 74, name: "John Field" },
    { id: 12, name: "César Franck" },
    { id: 58, name: "Girolamo Frescobaldi" },
    { id: 136, name: "George Gershwin" },
    { id: 14, name: "Carlo Gesualdo" },
    { id: 151, name: "Orlando Gibbons" },
    { id: 32, name: "Alberto Ginastera" },
    { id: 95, name: "Philip Glass" },
    { id: 179, name: "Alexander Glazunov" },
    { id: 85, name: "Reinhold Glière" },
    { id: 156, name: "Mikhail Ivanovich Glinka" },
    { id: 92, name: "Christoph Willibald von Gluck" },
    { id: 1, name: "Karl Goldmark" },
    { id: 207, name: "Antonio Carlos Gomes" },
    { id: 16, name: "Henryk Górecki" },
    { id: 70, name: "Morton Gould" },
    { id: 29, name: "Charles Gounod" },
    { id: 99, name: "Percy Grainger" },
    { id: 76, name: "Enrique Granados" },
    { id: 162, name: "Edvard Grieg" },
    { id: 172, name: "Sofia Gubaidulina" },
    { id: 67, name: "George Frideric Handel" },
    { id: 42, name: "Howard Hanson" },
    { id: 201, name: "Roy Harris" },
    { id: 208, name: "Franz Joseph Haydn" },
    { id: 155, name: "Hans Werner Henze" },
    { id: 94, name: "Victor Herbert" },
    { id: 154, name: "Paul Hindemith" },
    { id: 158, name: "Vagn Holmboe" },
    { id: 75, name: "Gustav Holst" },
    { id: 200, name: "Arthur Honegger" },
    { id: 30, name: "Johann Nepomuk Hummel" },
    { id: 15, name: "Engelbert Humperdinck" },
    { id: 122, name: "Jacques Ibert" },
    { id: 217, name: "Charles Ives" },
    { id: 96, name: "Leoš Janáček" },
    { id: 23, name: "Clément Janequin" },
    { id: 148, name: "Scott Joplin" },
    { id: 63, name: "Dmitry Kabalevsky" },
    { id: 218, name: "Aram Khachaturian" },
    { id: 34, name: "Zoltán Kodály" },
    { id: 7, name: "Erich Wolfgang Korngold" },
    { id: 59, name: "Edouard Lalo" },
    { id: 88, name: "Orlande de Lassus" },
    { id: 194, name: "Ruggero Leoncavallo" },
    { id: 220, name: "Léonin" },
    { id: 26, name: "György Ligeti" },
    { id: 197, name: "Franz Liszt" },
    { id: 119, name: "Fernando Lopes-Graça" },
    { id: 10, name: "Jean-Baptiste Lully" },
    { id: 142, name: "Witold Lutoslawski" },
    { id: 114, name: "Edward MacDowell" },
    { id: 157, name: "Guillaume de Machaut" },
    { id: 77, name: "Gustav Mahler" },
    { id: 204, name: "Marin Marais" },
    { id: 177, name: "Benedetto Marcello" },
    { id: 187, name: "Alessandro Marcello" },
    { id: 11, name: "Bohuslav Martinů" },
    { id: 69, name: "Pietro Mascagni" },
    { id: 124, name: "Jules Massenet" },
    { id: 147, name: "Felix Mendelssohn" },
    { id: 150, name: "Olivier Messiaen" },
    { id: 64, name: "Francisco Mignone" },
    { id: 121, name: "Darius Milhaud" },
    { id: 164, name: "Ernest Moeran" },
    { id: 39, name: "Claudio Monteverdi" },
    { id: 196, name: "Wolfgang Amadeus Mozart" },
    { id: 181, name: "Modest Mussorgsky" },
    { id: 52, name: "Carl Nielsen" },
    { id: 111, name: "Luigi Nono" },
    { id: 28, name: "Jacob Obrecht" },
    { id: 117, name: "Johannes Ockeghem" },
    { id: 134, name: "Jacques Offenbach" },
    { id: 93, name: "Carl Orff" },
    { id: 115, name: "Johann Pachelbel" },
    { id: 3, name: "Niccolò Paganini" },
    { id: 214, name: "Giovanni Pierluigi da Palestrina" },
    { id: 5, name: "Arvo Pärt" },
    { id: 203, name: "Krzysztof Penderecki" },
    { id: 113, name: "Giovanni Battista Pergolesi" },
    { id: 219, name: "Pérotin" },
    { id: 40, name: "Astor Piazzolla" },
    { id: 202, name: "Francis Poulenc" },
    { id: 78, name: "Michael Praetorius" },
    { id: 185, name: "Sergei Prokofiev" },
    { id: 146, name: "Giacomo Puccini" },
    { id: 199, name: "Henry Purcell" },
    { id: 188, name: "Sergei Rachmaninoff" },
    { id: 178, name: "Jean-Philippe Rameau" },
    { id: 100, name: "Einojuhani Rautavaara" },
    { id: 57, name: "Maurice Ravel" },
    { id: 72, name: "Max Reger" },
    { id: 176, name: "Steve Reich" },
    { id: 173, name: "Ottorino Respighi" },
    { id: 90, name: "Wolfgang Rihm" },
    { id: 118, name: "Nikolai Rimsky-Korsakov" },
    { id: 215, name: "Joaquín Rodrigo" },
    { id: 107, name: "Ned Rorem" },
    { id: 60, name: "Gioachino Rossini" },
    { id: 140, name: "Albert Roussel" },
    { id: 45, name: "Camille Saint-Saëns" },
    { id: 143, name: "Antonio Salieri" },
    { id: 104, name: "Erik Satie" },
    { id: 97, name: "Domenico Scarlatti" },
    { id: 65, name: "Alessandro Scarlatti" },
    { id: 160, name: "Franz Schmidt" },
    { id: 137, name: "Alfred Schnittke" },
    { id: 62, name: "Arnold Schoenberg" },
    { id: 183, name: "Franz Schubert" },
    { id: 24, name: "William Schuman" },
    { id: 129, name: "Robert Schumann" },
    { id: 191, name: "Heinrich Schütz" },
    { id: 18, name: "Alexander Scriabin" },
    { id: 46, name: "Dmitri Shostakovich" },
    { id: 186, name: "Jean Sibelius" },
    { id: 211, name: "Bedrich Smetana" },
    { id: 212, name: "Fernando Sor" },
    { id: 166, name: "Louis Spohr" },
    { id: 209, name: "Carl Stamitz" },
    { id: 4, name: "Wilhelm Stenhammar" },
    { id: 101, name: "Karlheinz Stockhausen" },
    { id: 171, name: "Richard Strauss" },
    { id: 165, name: "Johann Strauss Jr" },
    { id: 190, name: "Igor Stravinsky" },
    { id: 33, name: "Josef Suk" },
    { id: 182, name: "Jan Pieterszoon Sweelinck" },
    { id: 49, name: "Karol Szymanowski" },
    { id: 213, name: "Toru Takemitsu" },
    { id: 126, name: "Thomas Tallis" },
    { id: 167, name: "Giuseppe Tartini" },
    { id: 54, name: "John Taverner" },
    { id: 79, name: "Pyotr Ilyich Tchaikovsky" },
    { id: 83, name: "Georg Philipp Telemann" },
    { id: 13, name: "Michael Tippett" },
    { id: 22, name: "Edgard Varèse" },
    { id: 36, name: "Ralph Vaughan Williams" },
    { id: 35, name: "Giuseppe Verdi" },
    { id: 205, name: "Tomás Luis de Victoria" },
    { id: 55, name: "Heitor Villa-Lobos" },
    { id: 98, name: "Antonio Vivaldi" },
    { id: 138, name: "Richard Wagner" },
    { id: 44, name: "William Walton" },
    { id: 168, name: "Carl Maria von Weber" },
    { id: 6, name: "Anton Webern" },
    { id: 131, name: "Kurt Weill" },
    { id: 41, name: "Charles-Marie Widor" },
    { id: 161, name: "Hugo Wolf" },
    { id: 17, name: "Iannis Xenakis" },
    { id: 141, name: "Eugene Ysaÿe" },
    { id: 25, name: "Alexander von Zemlinsky" },
];

export default composerList;